tripod/app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('exp/<int:experiment_id>/', views.exp, name='exp'),
    path('config/<int:config_id>/', views.config, name='config'),
    path('exp/add/', views.addexp, name='addexp'),
    path('config/add/<int:experiment_id>', views.addconfig, name='addconfig'),
]

tripod/tripod/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

tripod/app/models.py
from django.db import models
from django.forms import ModelForm
from django.forms import widgets
import datetime


class Experiment(models.Model):
    experiment_name = models.CharField(max_length=200, unique=True)
    pub_date = models.DateTimeField('date published', default=datetime.date.today)
    settings = models.TextField()

    def __str__(self):
        return self.experiment_name


class Config(models.Model):
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)
    config_name = models.CharField(max_length=200, unique=True)
    config_settings = models.TextField()
    pub_date = models.DateTimeField('date published', default=datetime.date.today)

    def __str__(self):
        return self.config_name


class ExperimentForm(ModelForm):
    class Meta:
        model = Experiment
        fields = ['experiment_name', 'settings']
        widgets = {
            'experiment_name': widgets.TextInput(attrs={'class': 'form-control'}),
            'settings': widgets.Textarea(attrs={'class': 'form-control'}),

        }


class ConfigForm(ModelForm):
    class Meta:
        model = Config
        fields = ['experiment', 'config_name', 'config_settings']
        widgets = {
            'experiment': widgets.Select(attrs={'class': 'form-control'}),
            'config_name': widgets.TextInput(attrs={'class': 'form-control'}),
            'config_settings': widgets.Textarea(attrs={'class': 'form-control'}),
        }

tripod/app/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Experiment, Config, ExperimentForm, ConfigForm
from django.shortcuts import render, get_object_or_404
from .core.default import Nodes, GPUs
from .core.checker import check_config_settings, check_experiment_settings

def index(request):
    experiments_list = Experiment.objects.order_by('-pub_date')
    context = {'experiments_list': experiments_list}
    return render(request, 'app/index.html', context)


def exp(request, experiment_id):
    experiment = get_object_or_404(Experiment, pk=experiment_id)
    context = {'experiment': experiment}
    return render(request, 'app/exp.html', context)


def addexp(request):

    if request.method == 'POST':
        form = ExperimentForm(request.POST)
        if form.is_valid():

            # flag, error = check_settings(form.cleaned_data['settings'])
            # if flag:
            form.save()
            return HttpResponseRedirect('/app/')

    else:
        form = ExperimentForm()

    context = {'form': form}

    return render(request, 'app/addexp.html', context)


def config(request, config_id):
    config = get_object_or_404(Config, pk=config_id)

    if request.method == 'POST':



        print(request.POST)
        context = {
                    'config': config,
                    'scripts': '1',
                    'error': '2',
                    'nodes': Nodes,
                    'gpus': GPUs,
                   }
        return render(request, 'app/config.html', context)

    else:
        context = {
                    'config': config,
                    'nodes': Nodes,
                    'gpus': GPUs,
                   }
        return render(request, 'app/config.html', context)


def addconfig(request, experiment_id):
    experiment = get_object_or_404(Experiment, pk=experiment_id)
    error = ''

    if request.method == 'POST':
        form = ConfigForm(request.POST)
        if form.is_valid():
            add_exp_id = form.cleaned_data['experiment'].id

            settings = form.cleaned_data['config_settings']
            error += check_config_settings(settings)
            print(settings, error)
            if error:
                context = {'form': form, 'experiment': experiment, 'error': error}
                return render(request, 'app/addconfig.html', context)
            else:
                form.save()

                return HttpResponseRedirect('/app/exp/{}'.format(add_exp_id))
        else:
            error += "Invalid Form"

    else:
        form = ConfigForm()

    context = {'form': form, 'experiment': experiment, 'error': error}

    return render(request, 'app/addconfig.html', context)

tripod/app/templates/app/addconfig.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tripod</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.5.0/styles/github.min.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.5.0/highlight.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.5.0/languages/python.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </head>
  <body>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
          <a href="/app/">Tripod</a>
      </ol>
    </nav>

    <div class="container" role="main">
        <div class="row">
            <h1> {{ experiment.experiment_name }}</h1>
        </div>
        <div class="row">
            <h2> Basic Settings</h2>
        </div>
        <div class="row">
            <pre><code class="language-python"> {{ experiment.settings }} </code></pre>
        </div>

        <div class="row">
            <h2>Add New Configs</h2>
        </div>


        <div class="row">
        <form action="{% url 'addconfig' experiment.id %}" method="post">

            {% csrf_token %}
            <div class="form-group">
                {% if form.experiment.errors %}
                    <div class="alert alert-danger" role="alert"> {{ form.experiment.errors }} </div>
                {% endif %}

                <label for="experiment_name">For Experiment: </label>
                {{ form.experiment }}
            </div>

            <div class="form-group">
                {% if form.config_name.errors %}
                    <div class="alert alert-danger" role="alert"> {{ form.config_name.errors }} </div>
                {% endif %}
                <label for="experiment_name">Config Name</label>
                {{ form.config_name }}
            </div>

            <div class="form-group">
                {% if form.config_settings.errors %}
                    <div class="alert alert-danger" role="alert"> {{ form.config_settings.errors }} </div>
                {% endif %}
                <label for="experiment_name">Config Setting</label>
                {{ form.config_settings }}
            </div>

            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}

            <button type="submit" class="btn btn-primary">Submit</button>

        </form>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

tripod/app/templates/app/addexp.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tripod</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.5.0/styles/github.min.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.5.0/highlight.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.5.0/languages/python.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </head>
  <body>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
          <a href="/app/">Tripod</a>
      </ol>
    </nav>

    <div class="container" role="main">

        <div class="row">
            <h1>Add Experiments</h1>
        </div>

        <div class="row">
            <form action="{% url 'addexp' %}" method="post">

                {% csrf_token %}

                <div class="form-group">
                    {{ form.experiment_name.errors }}
                    <label for="experiment_name">Experiment Name</label>
                    {{ form.experiment_name }}
                </div>

                <div class="form-group">
                    {{ form.settings.errors }}
                    <label for="experiment_name">Experiment General Setting</label>
                    {{ form.settings }}
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>

            </form>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

tripod/app/templates/app/config.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tripod</title>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="//at.alicdn.com/t/font_2372945_kpbt8qghfb.css">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.5.0/styles/github.min.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.5.0/highlight.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/highlight.js/10.5.0/languages/python.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

  </head>
  <body>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
          <a href="/app/">Tripod</a>
      </ol>
    </nav>

    <div class="container" role="main">
        <div class="row">
            <h1> {{ config.config_name }} </h1>
        </div>

        <div class="row">
            <p> {{ config.pub_date }} </p>
        </div>

        <div class="row">
            <pre><code class="language-python"> {{ config.config_settings }} </code></pre>
        </div>

        <form action="{% url 'config' config.id %}" method="post">
        {% csrf_token %}

        <ul class="list-group row">


            {% for node in nodes %}
              <li class="list-group-item col-sm-3">
              <div class="form-check-inline col-sm-2">
                  <i class="iconfont icon-xianqia-copy pr-1"> </i>{{ node }}
              </div>
              {% for gpu in gpus %}
                <div class="form-check form-check-inline col-sm-1">
                  <input class="form-check-input" type="checkbox" id="inlineCheckbox1" name="option-{{ node }}-{{ gpu }}">
                </div>
              {% endfor %}
              </li>
            {% endfor %}

        </ul>


        <div class="row pt-5">
            <button type="submit" class="btn btn-primary">Gen Scripts</button>
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
        </div>

        </form>



    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

tripod/app/templates/app/exp.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tripod</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  </head>
  <body>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
          <a href="/app/">Tripod</a>
      </ol>
    </nav>

    <div class="container" role="main">
        <div class="row">
            <h1> {{ experiment.experiment_name }}</h1>
        </div>
        <div class="row">
            <h2> Basic Settings</h2>
            <code> {{ experiment.settings }} </code>
        </div>

        <div class="row">
            <h2>All Configs</h2>
        </div>


        <div class="row">
            <ul>
            {% for config in experiment.config_set.all %}
                <li><a href="{% url 'config' config.id %}">{{ config.config_name }} - {{ config.pub_date }}</a></li>
            {% endfor %}
            </ul>
        </div>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

tripod/app/templates/app/index.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tripod</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  </head>
  <body>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
          <a href="/app/">Tripod</a>
      </ol>
    </nav>

    <div class="container" role="main">
        <div class="row">
            <h1>All Experiments</h1>
        </div>

        <div class="row pt-3">
            {% if experiments_list %}
                <ul class="list-group">
                {% for experiment in experiments_list %}
                    <li class="list-group-item"><a href="{% url 'exp' experiment.id %}">{{ experiment.experiment_name }} - {{ experiment.pub_date }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No experiments are available.</p>
            {% endif %}
        </div>

        <div class="row pt-3">

            <form action="{% url 'addexp' %}", method="get">
              <input type="submit" class="btn btn-primary" value="Add Experiment">
            </form>

        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>